#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.


menuentry "Ubuntu xxLive" {
 set root=(hd0,2)
 loopback loop /home/arthur/Downloads/ubuntu-16.04.3-custom-amd64.iso
 linux (loop)/install/vmlinuz boot=install iso-scan/filename=/home/arthur/Downloads/ubuntu-16.04.3-custom-amd64.iso noprompt noeject
 initrd (loop)/install/initrd.gz
}
